<?php
$aMenuLinks = array(
    array(
        "О компании",
        "./",
        array(),
        array(),
        ""
    ),
    array(
        "Руководство",
        "management.php",
        array(),
        array(),
        ""
    ),
    array(
        "Миссия и стратегия",
        "mission.php",
        array(),
        array(),
        ""
    ),
    array(
        "История",
        "history.php",
        array(),
        array(),
        ""
    ),
    array(
        "Вакансии",
        "vacancies.php",
        array(),
        array(),
        ""
    ),
    array(
        "Отзывы",
        "/company/reviewed.php",
        array(),
        array(),
        ""
    )
);
?>